# Generated by Django 2.2.dev20181118002753 on 2018-12-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='uploader.Tag'),
        ),
    ]
